# AS		= as
# LD		= ld
# CC		= gcc
# CPP		= $(CC) -E
# AR		= ar
# NM		= nm
# LDR		= ldr
# STRIP		= strip
# OBJCOPY		= objcopy
# OBJDUMP		= objdump

objects = main.o kbd.o command.o display.o \
	insert.o search.o files.o utils.o

edit: $(objects)
	cc -o edit $(objects)

$(objects): defs.h
kbd.o command.o files.o: command.h
display.o insert.o search.o files.o: buffer.h

.PHONY: clean
clean:
	rm edit $(objects)
